Hw02 unpack string
SomchaiSPB/otus-golang-hw pull request #3
Opened 2021-09-11 15:12 UTC by SomchaiSPB

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-09-24 15:40 UTC, kulti requested changes
Денис, спасибо за вариант решения.

В этом ПР'е множество проблем в разных областях.

**Самое важное** — некорректная работа со строками. Обращение по индексу вернет байт, не символ. Из-за этого текущий алгоритм будет некорректно работать со строками с мультибайтовыми символами (например, с рускими буквами). В этой теме очень важно разобраться. В этом и суть ДЗ — разобраться со строками. Почитать про строки можно тут — https://go.dev/blog/strings. Так же можно прийти и спросить в слаке, или на любом занятии (для этого есть 15 до занятия и, иногда после занятия есть время).

Чуть менее важно, но тоже важно — неоптимальная работа со строками. Это опять же из-за непонимания сути строк в Go. В соотвествующем дискашене предложил вам изучить `strings.Builder`.

Нет тестов. Работающее решение написанное чисто и ясно — это 6 баллов, т.е. незачет. Нужно еще подумать над тестами, чтобы получить баллы до зачета (от 7 баллов).

Кажется, есть некоторые проблемы в работе с git. В ПР (ветку) попал лишний код. Его тут быть не должно. Каждая ДЗ делается в своей ветке.

Так же зачем-то удалены .sync файлы от других ДЗ. Если это сделано с пониманием, то хорошо. Если «случайно», то не хорошо :) Если что, вот тут объяснено, зачем эти файлы нужны — https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2.

2021-09-24 15:40 UTC, kulti commented on hw03_frequency_analysis/top.go
>  package hw03frequencyanalysis
Это от другого ДЗ. Нужно убрать из этого ПР'a.

2021-09-24 15:40 UTC, kulti commented on main.go
> +package main
Это тоже к ДЗ не относится. В принципе непонятно, к чему именно относится :)

2021-09-24 15:40 UTC, kulti commented on hw02_unpack_string/unpack_test.go
> +			fmt.Println(result)
Зачем тут эта строчка?

2021-09-24 15:40 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	if unicode.IsNumber(rune(s[0])) {
Это некорректно. s[0] — вернет байт. Если в начале строки будет мультибайтовый символ, то получится «ерунда».

2021-09-24 15:40 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	runeArr := s
В чем смысл этого копирования строки?

2021-09-24 15:40 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			result += string(cur)
Такая работа со строка сильно затратная по памяти. Строки в го незименяемые. Каждый раз будет выделяться память под новую строку и будет происходить копирование данных. Посмотрите на `strings.Builder`. Он поможет сделать решение оптимальнее.

2021-09-26 19:50 UTC, kulti approved these changes
Решение все еще неоптимальное, но это не тема этого ДЗ.

ДЗ принято — 9/10. Можно немного почистить код от лишнего, будет +1 балл.

2021-09-26 19:50 UTC, kulti commented on hw02_unpack_string/unpack_test.go
> +func TestUnpackRussian(t *testing.T) {
Этот тест полностью дублирует то, что написано в `TestUnpack`.

2021-09-26 19:50 UTC, kulti commented on hw02_unpack_string/unpack.go
> +				continue
Надеюсь, вы понимаете, что в этом if'e куча копирований. Если да, то это вопрос алгоритма (как быть с 0), не того, как код на Go писать. Про алгоритм можно будет из разбора узнать, если ничего не придумается.

2021-09-26 19:50 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	runeArr := []rune(s)
Не понял, зачем нужно это копирование. Цикл `for range` по строке будет идти по-рунно. А прямое использование только одно — `runeArr[i-1]`, которое, по сути уже есть в prev.

2021-09-26 19:50 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		}
Есть большие сомнения в необходимости этого if'a.

2021-10-02 17:13 UTC, SomchaiSPB commented on hw02_unpack_string/unpack.go
> +		}
По моему я это сделал, чтобы определить сразу prev, который на первой итерации имеет значение nil, чтобы не падало дальше с ошибкой nil reference.

2021-10-02 17:14 UTC, SomchaiSPB commented on hw02_unpack_string/unpack.go
> +	runeArr := []rune(s)
Это копирование нужно, чтобы получить нормальные ключи внутри массива рун (из лекции взял). Если убрать это копирование, то с кириллицей выдает абракадабру.  Возможно, есть другое решение.

2021-10-02 17:16 UTC, SomchaiSPB commented on hw02_unpack_string/unpack.go
> +				continue
Да, тут куча копирований строк =) пока не додумался как иначе убрать 1 руну перед 0. Либо была мысль не писать руну в результат до того как пройдут все проверки, но это пол решения переписывать надо будет.
С алгоритмами у меня не особо хорошо, согласен.

2021-10-02 17:16 UTC, SomchaiSPB commented on hw02_unpack_string/unpack_test.go
> +func TestUnpackRussian(t *testing.T) {
Исправил. Видимо забыл удалить этот тест.

2021-10-02 20:01 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		}
rune это число. Если есть какой-то нюанс, то надо на это тест написать. Я удалял этот код — тесты проходили :)

2021-10-02 20:02 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	runeArr := []rune(s)
Посмотрите внимательно мой комментарий. Там рассказано, как пройти строк по рунам без копирования ;)

2021-12-18 17:26 UTC, merged