Hw03 frequency analysis
SomchaiSPB/otus-golang-hw pull request #4
Opened 2021-09-20 17:16 UTC by SomchaiSPB

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [x] Пайплайн зелёный - 4 балла
- [x] Добавлены новые юнит-тесты - до 4 баллов
- [x] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-09-22 12:09 UTC, agneum requested changes
Спасибо за выполненное задание. 
Хорошая работа, однако принять не могу, потому что не добавлены новые тесты
Итого: 6 баллов из 10

2021-09-22 12:09 UTC, agneum commented on hw02_unpack_string/go.mod
> +module github.com/SomchaiSPB/otus-golang-hw/hw02_unpack_string
Желательно включать в Pull Request только релевантные файлы

2021-09-22 12:09 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	}
Зная `size`, оптимальнее будет обойти только нужное количество элементов списка и переложить их в слайс

2021-09-22 12:09 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	sort.Sort(sort.Reverse(result))
Чуть компактнее будет выглядеть сортировка с помощью https://pkg.go.dev/sort#Slice - не требует создания структуры и объявления методов

2021-09-22 12:09 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	output := make([]string, 0)
Можно сразу задать capacity для слайса

2021-09-26 10:58 UTC, SomchaiSPB commented on hw03_frequency_analysis/top.go
> +	output := make([]string, 0)
Когда задаю капасити для слайса, то получается некорректный вывод, не понимаю с чем это связано.
Код:

```
func (l List) ToStringArray(size int) []string {
	output := make([]string, len(l))
```
Ошибка в тесте:

```
Error:      	Not equal: 
        	            	expected: []string{"он", "а", "и", "ты", "что", "-", "Кристофер", "если", "не", "то"}
        	            	actual  : []string{"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "он", "а", "и", "ты", "что", "-", "Кристофер", "если", "не", "то"}
```

2021-09-27 02:32 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	output := make([]string, 0)
В данном случае задаётся длина слайса, а затем выполняются append.
Чтобы задать только capacity, нужно указать нулевую длину и capacity: 
`output := make([]string, 0, len(l))`

2021-09-27 02:33 UTC, agneum approved these changes
Спасибо за правки
10/10

2021-09-29 08:00 UTC, merged